spring.datasource.url=jdbc:h2:mem:testdb

spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.web.open-browser=true

jwt.secret=meinSuperGeheimerSchluesselDerMindestens256BitsLangIst12345678
jwt.expiration=86400000